version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/iss_aws
permissions:
   - object: /var/www/html/iss_aws
     pattern: "**"
     owner: nginx
     group: nginx
     mode: 755
     type:
       - file
